"""Microsoft Entra ID and Microsoft 365 tables."""
from __future__ import annotations

from .base import PLATFORM, TableSchema, register

DOCS = "https://learn.microsoft.com/azure/azure-monitor/reference/tables"

# Columns shared by SigninLogs and AADNonInteractiveUserSignInLogs. The two
# tables are near-identical in Sentinel — which is exactly why hunts miss things:
# an analyst querying only SigninLogs never sees token-refresh activity, and
# non-interactive volume is roughly 10x interactive in a real tenant.
_SIGNIN_CORE: tuple[tuple[str, str], ...] = (
    ("ResourceId", "string"),
    ("OperationName", "string"),
    ("OperationVersion", "string"),
    ("Category", "string"),
    ("ResultType", "string"),
    ("ResultSignature", "string"),
    ("ResultDescription", "string"),
    ("DurationMs", "long"),
    ("CorrelationId", "string"),
    ("Identity", "string"),
    ("Level", "string"),
    ("Location", "string"),
    ("AlternateSignInName", "string"),
    ("AppDisplayName", "string"),
    ("AppId", "string"),
    ("AppliedConditionalAccessPolicies", "dynamic"),
    ("AuthenticationDetails", "dynamic"),
    ("AuthenticationMethodsUsed", "dynamic"),
    ("AuthenticationProcessingDetails", "dynamic"),
    ("AuthenticationRequirement", "string"),
    ("ClientAppUsed", "string"),
    ("ConditionalAccessStatus", "string"),
    ("CreatedDateTime", "datetime"),
    ("DeviceDetail", "dynamic"),
    ("HomeTenantId", "string"),
    ("IPAddress", "string"),
    ("IsInteractive", "bool"),
    ("IsRisky", "bool"),
    ("LocationDetails", "dynamic"),
    ("MfaDetail", "dynamic"),
    ("NetworkLocationDetails", "dynamic"),
    ("OriginalRequestId", "string"),
    ("ProcessingTimeInMs", "int"),
    ("ResourceDisplayName", "string"),
    ("ResourceIdentity", "string"),
    ("ResourceTenantId", "string"),
    ("RiskDetail", "string"),
    ("RiskEventTypes_V2", "dynamic"),
    ("RiskLevelAggregated", "string"),
    ("RiskLevelDuringSignIn", "string"),
    ("RiskState", "string"),
    ("SignInIdentifier", "string"),
    ("SignInIdentifierType", "string"),
    ("Status", "dynamic"),
    ("TokenIssuerName", "string"),
    ("TokenIssuerType", "string"),
    ("UserAgent", "string"),
    ("UserDisplayName", "string"),
    ("UserId", "string"),
    ("UserPrincipalName", "string"),
    ("UserType", "string"),
)

SigninLogs = register(TableSchema(
    name="SigninLogs",
    family="entra",
    columns=PLATFORM + _SIGNIN_CORE,
    docs=f"{DOCS}/signinlogs",
    description="Interactive Entra ID sign-ins.",
))

AADNonInteractiveUserSignInLogs = register(TableSchema(
    name="AADNonInteractiveUserSignInLogs",
    family="entra",
    columns=PLATFORM + _SIGNIN_CORE,
    docs=f"{DOCS}/aadnoninteractiveusersigninlogs",
    description="Token refreshes and other non-interactive sign-ins. "
                "Roughly 10x the volume of SigninLogs in a real tenant.",
))

AADServicePrincipalSignInLogs = register(TableSchema(
    name="AADServicePrincipalSignInLogs",
    family="entra",
    columns=PLATFORM + (
        ("OperationName", "string"),
        ("Category", "string"),
        ("ResultType", "string"),
        ("ResultDescription", "string"),
        ("CorrelationId", "string"),
        ("Identity", "string"),
        ("Location", "string"),
        ("AppId", "string"),
        ("IPAddress", "string"),
        ("ResourceDisplayName", "string"),
        ("ResourceIdentity", "string"),
        ("ResourceTenantId", "string"),
        ("ServicePrincipalId", "string"),
        ("ServicePrincipalName", "string"),
        ("ServicePrincipalCredentialKeyId", "string"),
        ("ServicePrincipalCredentialThumbprint", "string"),
        ("ConditionalAccessStatus", "string"),
        ("LocationDetails", "dynamic"),
        ("Status", "dynamic"),
        ("UniqueTokenIdentifier", "string"),
    ),
    docs=f"{DOCS}/aadserviceprincipalsigninlogs",
    description="Workload identity (app / service principal) sign-ins.",
))

AuditLogs = register(TableSchema(
    name="AuditLogs",
    family="entra",
    columns=PLATFORM + (
        ("ResourceId", "string"),
        ("OperationName", "string"),
        ("OperationVersion", "string"),
        ("Category", "string"),
        ("ResultType", "string"),
        ("ResultDescription", "string"),
        ("ResultReason", "string"),
        ("CorrelationId", "string"),
        ("Level", "string"),
        ("DurationMs", "long"),
        ("Identity", "string"),
        ("ActivityDisplayName", "string"),
        ("ActivityDateTime", "datetime"),
        ("LoggedByService", "string"),
        ("AADOperationType", "string"),
        ("InitiatedBy", "dynamic"),
        ("TargetResources", "dynamic"),
        ("AdditionalDetails", "dynamic"),
    ),
    docs=f"{DOCS}/auditlogs",
    description="Entra ID directory changes: role grants, app credentials, user creation.",
))

OfficeActivity = register(TableSchema(
    name="OfficeActivity",
    family="entra",
    columns=PLATFORM + (
        ("OfficeWorkload", "string"),
        ("Operation", "string"),
        ("RecordType", "string"),
        ("OfficeObjectId", "string"),
        ("UserId", "string"),
        ("UserKey", "string"),
        ("UserType", "string"),
        ("ClientIP", "string"),
        ("UserAgent", "string"),
        ("ResultStatus", "string"),
        ("OrganizationId", "string"),
        ("OrganizationName", "string"),
        ("Site_Url", "string"),
        ("SourceFileName", "string"),
        ("SourceFileExtension", "string"),
        ("SourceRelativeUrl", "string"),
        ("MailboxOwnerUPN", "string"),
        ("Subject", "string"),
        ("Logon_Type", "string"),
        ("ClientInfoString", "string"),
        ("Parameters", "dynamic"),
        ("ClientProcessName", "string"),
    ),
    docs=f"{DOCS}/officeactivity",
    description="Exchange, SharePoint and OneDrive activity from the unified audit log.",
))

CloudAppEvents = register(TableSchema(
    name="CloudAppEvents",
    family="entra",
    columns=PLATFORM + (
        ("ActionType", "string"),
        ("Application", "string"),
        ("ApplicationId", "int"),
        ("AccountObjectId", "string"),
        ("AccountId", "string"),
        ("AccountDisplayName", "string"),
        ("IsAdminOperation", "bool"),
        ("DeviceType", "string"),
        ("OSPlatform", "string"),
        ("IPAddress", "string"),
        ("IsAnonymousProxy", "bool"),
        ("CountryCode", "string"),
        ("City", "string"),
        ("ISP", "string"),
        ("UserAgent", "string"),
        ("ActivityType", "string"),
        ("ActivityObjects", "dynamic"),
        ("ObjectName", "string"),
        ("ObjectType", "string"),
        ("ObjectId", "string"),
        ("ReportId", "string"),
        ("RawEventData", "dynamic"),
        ("AccountType", "string"),
    ),
    docs="https://learn.microsoft.com/defender-xdr/advanced-hunting-cloudappevents-table",
    description="Defender for Cloud Apps activity across SaaS applications.",
))
